default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 2797416

development:
  <<: *default
  database: microposts_app_development

test:
  <<: *default
  database: microposts_app_test
